<?php

/**
 * @file
 * Contains push_notifications.module functionality.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Link;

/**
 * OS device network IDs.
 */
const PUSH_NOTIFICATIONS_NETWORK_IOS = 'ios';
const PUSH_NOTIFICATIONS_NETWORK_ANDROID = 'android';

/**
 * Denotes that the push notification is not send, just saved as draft.
 */
const PUSH_NOTIFICATION_DRAFT = 0;

/**
 * Denotes that the push notification is send.
 */
const PUSH_NOTIFICATION_SENT = 1;

/**
 * Implements hook_help().
 */
function push_notifications_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the push_notifications module.
    case 'help.page.push_notifications':
      $PushHandler = \Drupal::service('push_notifications.message_sender_accounts');
      $PushHandler->setAccounts(array(Drupal::currentUser()));
      $PushHandler->setMessage('This is my test payload.');
      $PushHandler->dispatch();

      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Push notification functionality for iPhone and Android.') . '</p>';
      $output .= '<p>' . t('The full documentation is available online: <a href="@doc_url" target="_blank">Documentation</a >.', array(
        '@doc_url' => 'https://www.drupal.org/node/2718063'
        )) . '</p>';

      $output .= '<p>' . t('You can manually send out a push notification @message_link.', array(
          '@message_link' => Link::createFromRoute('from the admin section', 'push_notifications.send_message_form')->toString(),
        )) . '</p>';
      return $output;
  }
}

/**
 * Send a push notification through the FCM service
 *
 * @param $tokens
 * @param $body
 * @param $title
 * @param $priority
 * @param array $data_payload
 *
 * @return mixed
 */
function send_push_notification_fcm($tokens, $body, $title, $priority, $data_payload = array()) {
  // Allow other modules to alter the $messageSend before sending the
  // notifications by invoking: hook_push_notifications_fcm_alter().
  \Drupal::moduleHandler()->alter('send_push_notification_fcm', $tokens, $body, $title, $priority, $data_payload);

  $messageSender = \Drupal::service('push_notifications.firebase_devices');
  $messageSender->setTokens($tokens);
  $messageSender->setNotification($body, $title);
  $messageSender->setPriority($priority);
  $messageSender->setDataPayload($data_payload);
  $messageSender->sendBroadcast();

  return $messageSender->getResults();
}