# Schema for the configuration files of the Push Notifications module.
push_notifications.fcm:
  type: config_object
  label: 'FCM Key'
  mapping:
      api_key:
        type: string
        label: 'FCM Key'